language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN='cc17ca84-3696-463a-afed-fdac392fbf56'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - rail.himax1982@gmail.com
    on_success: never # default: change
    on_failure: always # default: always